import { DropdownMenu } from "@radix-ui/react-dropdown-menu";
import type {} from "@radix-ui/react-dropdown-menu";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-4xl font-black">CSS Figma challenge 999</h1>
    </div>
  );
};

export default Home;
